#!/usr/bin/env bash
# displays 'To infinity and beyond' indefinitely and 
# "I am invincible" when recieving a termination signal

while true;
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
