#!/usr/bin/env bash
# Configures an Ubuntu server to change localhost and facebook.com Ip addresses

cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2 localhost\n8.8.8.8 facebook.com/" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
